### ISSUE TITLE
Stepwise elimination nlme

### ISSUE THREAD

**Issue by Jasmine1990** [cvoeten/buildmer#1]
Hello!

I'm using builme to create a stepwise elimination, I was wondering if there was a way to keep certain fixed effects in the same way stepAIC has "scope=c(lower=~x, upper=full)".

Thanks! 
Jasmine

**Comment by cvoeten** [comment]
Hi Jasmine,

Thank you for the suggestion (and sorry for the delay in responding) -- I'll add functionality for this in the next release. In the mean time, you can edit buildmer's `fit` function using `fixInNamespace('fit','buildmer')` and add a line updating the formula to include the terms you want to be kept right before the call to `nlme::lme` is made.

Best,
Cesko

**Comment by cvoeten** [comment]
An 'include' argument has been added to all functions that causes terms to always be included in the formula. This is available in buildmer 1.1, which should make its way to CRAN shortly.

**Comment by phliulei** [comment]
Thank you for your great package. I want to keep fixed effects  `A*B`, but I get the error. 
> Error in `[<-.data.frame`(`*tmp*`, , p$crit.name, value = c(NA, NA, -4.87465714865097,  : 
  replacement has 5 rows, data has 9

This is the code (actually, I don't really know how to use the 'include' argument.) However, if the 'order' is deleted, it works.

```
fe <- DV~ 1 + A*B
m <- buildmer(f,data=exp3,direction=c('order','backward'),
              control=lmerControl(optimizer='bobyqa'),
              include = fe)
```

**Comment by cvoeten** [comment]
> Thank you for your great package. I want to keep fixed effects `A*B`, but I get the error.
> 
> > Error in `[<-.data.frame`(`*tmp*`, , p$crit.name, value = c(NA, NA, -4.87465714865097,  :
> > replacement has 5 rows, data has 9
> 
> This is the code (actually, I don't really know how to use the 'include' argument.) However, if the 'order' is deleted, it works.
> 
> ```
> fe <- DV~ 1 + A*B
> m <- buildmer(f,data=exp3,direction=c('order','backward'),
>               control=lmerControl(optimizer='bobyqa'),
>               include = fe)
> ```

Thanks for letting me know! It looks like you've indeed found a bug, probably in the 'order' routine. I've created a new issue for this problem: issue #3. Let's continue the conversation there. Could you please send me your data (or a fake dataset that results in the same error) so that I can investigate? Thanks!

**Comment by phliulei** [comment]
Sure, it's my pleasure, but can you give me your E-mail?
