### ISSUE TITLE
buildgamm4 unexpectedly tries to convert numeric to POSIXct

### ISSUE THREAD

**Issue by embiuw** [cvoeten/buildmer#11]
Hi,
I'm trying buildmer in order to obtain the optimal structure of a gamm4 model with several random smooths. Before trying on a small toy dataset, perhaps I can ask a quick question? I get an error at some stage after buildgamm4 has tested all models with only each separate smooth term. The error says:

Error in as.POSIXct.default(current) : 
  do not know how to convert 'current' to class “POSIXct”  

All my variables are numeric (integers or double), and there is not supposed to be any time structuring in my data. 

**My question is: is buildmer specifically expecting time structured data somehow?** 

Otherwise the error may come from inside lme4 somewhere, in which case I need to dig deeper. 

Very grateful for a simple first yes or no to my above question. 

Thanks!
Martin

**Comment by cvoeten** [comment]
No. Buildmer expects data to be formatted in the same way as gamm4.

In order to narrow down whether this is a bug in buildmer or in gamm4, it would help if you could share some data and code reproducing the issue.

**Comment by cvoeten** [comment]
Closing old.
