### ISSUE TITLE
Including uncorrelated random effects in buildGLMMAdaptive

### ISSUE THREAD

**Issue by sdevlin3001** [cvoeten/buildmer#14]
Hello,

Currently R errors when I include uncorrelated random effects in a model (I have tried both the lme4 syntax (||) or with the diag formulation you outline in the buildmer manual on p. 22-3). It says:

Fitting ML reference model
Error in p$fit(p, p$formula) : 
  mixed_model can only handle a single random-effect grouping factor, yet you seem to have specified 2

I understand that mixed_model cannot handle multiple random-effect grouping factors (yet), but it can handle uncorrelated random effects. Is there a simple way to work around this error? There seems to be a workaround for (g)lmer models, but that workaround is the precise cause of this error for buildGLMMadaptive. So another workaround would be much appreciated!

**Comment by cvoeten** [comment]
Thanks for the report. This was actually a relatively tough problem, but could you check if the current GH tip works for you?

**Comment by cvoeten** [comment]
Fixed in v2.4
