### ISSUE TITLE
buildmer() keep random effects

### ISSUE THREAD

**Issue by levossen** [cvoeten/buildmer#16]
Hi,
I have fitted a poisson glmer with an observation-level random effect to overcome overdispersion in poisson, quasipoisson and negative binomial glms. Buildmer outputs a glm which is again overdispersed. Is there a way to force buildmer to keep a random effect? 
Thanks!
Laura

**Comment by cvoeten** [comment]
The argument to 'include' is supposed to be a one-sided formula or a character vector, so unless you have an object named 'id' in your environment that evaluates to either ~(1|id) or "(1|id)", your specification will indeed not work; use either of these alternatives instead. It seems, then, that the bug you are reporting here is that the 'include' option isn't documented sufficiently clearly. Do you perhaps have any suggestions on how I can reword the documentation to make this option easier to use?

**Comment by levossen** [comment]
Thanks Cesko, 

An example of the use of include would be helpful I think. lmerTest::step function has a reduce.fixed and reduce.random argument, so perhaps keywords like "reduce" and "keep" in the description of 'include' would help find it? 

Still I haven't managed to get include to work..

´
ID <- "(1|dental.data$id)"
buildmer::buildmer(DT32 ~ Age*Gender*Smoking*Inj_group + ID, 
                   family=poisson, 
                   buildmerControl=buildmerControl(list(direction = "backward", include=ID)),
                   data=dental.data)
´

**Comment by cvoeten** [comment]
Hmm, it seems there also is a bug here - the way you're doing it is not how I would do it, but I would want it to work; and yet, when I try this (which is similar to what you are doing):

m <- buildmer(Reaction~Days,data=lme4::sleepstudy,buildmerControl=list(include='(1 | Subject)'))

I get a vague error. I need to investigate that. But in the meantime, for your case, this formulation should work just fine, and is also how I usually do this myself:

buildmer::buildmer(DT32 ~ Age/Gender/Smoking*Inj_group + ID,data=dental.data,family=poisson,buildmerControl=list(direction='backward',include=~(1|id)))

(although, is it correct that you've got both a variable 'ID', a fixed effect, and a variable 'id', a random-effect grouping factor? But this is up to you, not related to this bug report!)

Hope this helps, and thanks for reporting that the character-vector 'include' does not work as it should've.

**Comment by cvoeten** [comment]
I've now:

1. Fixed the bug preventing character-vector 'include's from working;
2. Added examples of the 'include' mechanism to the main `buildmer` command;
3. Fixed a different bug preventing 'includes' that do not include an intercept term from being processed correctly.

These fixes are all on GitHub now. Could you test whether they resolve the issue for you?

**Comment by mdokovova** [comment]
Hi! I'm not sure if the previous user resolved their problem, but when I try to make "include" work, the process simplifies the random structure. Here is an example:

random = ~(1 + Consonant | name)

buildmer::buildmer(MCI ~ PCC/age/Consonant + (1 + Consonant | speaker), data=ssd, buildmerControl=list(lmerControl(optimizer='bobyqa'), direction='backward', include=random))

I also tried :

buildmer::buildmer(MCI ~ PCC/age/Consonant + (1 + Consonant | speaker), data=ssd, buildmerControl=list(lmerControl(optimizer='bobyqa'), direction='backward', include= '(1 + Consonant | speaker)'))

In both cases the resulting model is MCI ~ 1 + PCC + PCC:age + (1 | speaker) whereas I would like to keep the maximal random structure (1+ Consonant | speaker). Do you think that this is a bug or have I used "include" incorrectly? 

Thank you in advance!

**Comment by cvoeten** [comment]
Can you send me your data and code? Your specification is correct, so this should work. The only reason I can think of is if your model isn't capable of converging with these random effects included. If you could send me your data and code (or simulated data that exhibits the same issue), I could check whether the problem is with your model or a bug in buildmer.

**Comment by mdokovova** [comment]
Thanks for the quick response! I have attached the data and a subsection of
the code. The model does converge with some warnings.

**Comment by cvoeten** [comment]
Not seeing any attachment - can you send me a link instead?

**Comment by mdokovova** [comment]
Here is a link, I've sent an email as well: https://drive.google.com/drive/folders/1x2FFEcncOzuKnAtmzMDtjj8dId484QaX?usp=share_link

**Comment by cvoeten** [comment]
It's your model:

Fitting via lmer, with ML: MCI ~ pcc_true/months/Consonant + (1 +
    Consonant | name.x)
boundary (singular) fit: see help('isSingular')
Convergence failure. Reducing terms and retrying... The failures were:
    lme4 reports not having converged (-1) Singular fit

'include' is not respected if it causes a convergence failure. Your variable 'Consonant' has ten levels, so you're estimating 90 random-effect coefficients - consider bringing it down to ten by dropping correlations. You would need to use the numeric values of your contrasts to do so - see the example in ?'diag,formula-method' for a suggestion. In any case, I don't think this is a bug in buildmer.

**Comment by mdokovova** [comment]
Thank you very much for checking, and thanks for developing this package!
