### ISSUE TITLE
Access to intermediate model results

### ISSUE THREAD

**Issue by bastianilso** [cvoeten/buildmer#18]
Hi,

As part of my research, I typically present which models were considered in a table and order the models by the criterion (deviance, AIC, LRR..)
So my question is, is it possible to access results from the intermediate models built by `buildmer`? I have tried inspecting the resulting model object, but it seems to only contain the anova results of the final model.

![image](https://user-images.githubusercontent.com/3967945/189834253-d1f9dab2-9f4a-4baa-ba59-c4f3832d5365.png)

**Comment by bastianilso** [comment]
@cvoeten thanks for your prompt reply!

I tried looking into `***@***.***$results`.
If I use the default direction `c(order, backwards)` I can access results in there and see the criterion results. Two questions:

1) What about the result of running an anova of each constructed model against the null model `(Pr(>Chisq))?`

2) Did I understand correctly that this seem to only cover the results from backwards elimination? If I use the direction `order` only, it seems that the `$results` variable is empty. (for info I am using `buildclmm` in this case)

**Comment by cvoeten** [comment]
Closing old.
