### ISSUE TITLE
backward elimination with glmer models

### ISSUE THREAD

**Issue by tmvchan** [cvoeten/buildmer#2]
Hello!

I've been using buildmer with a binomial distribution model - it successfully orders the variables for a maximal converging model, but errors are arising when trying to complete backward elimination (or forward, for that matter). It first was encountered with my own data, but I ran into the same thing with the default datasets and formulae provided in lme4:

bm.test <- buildmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
                     family = binomial, data = cbpp)

The above code gives me the resulting error:
Error in UseMethod("logLik") : 
  no applicable method for 'logLik' applied to an object of class "NULL"

Thanks,
Vanessa

**Comment by cvoeten** [comment]
Thanks for the report. You've actually found two bugs, one in backward() and one in forward(). The one in backward() was a silly oversight and easily fixed; I've just pushed a fix to github. I need to do some more thinking about what to do about forward().

As a workaround until a new version of buildmer is released (which will be a while as version 1.2.1 just came out and CRAN, understandably, do not appreciate rapid releases for small issues), buildglmmTMB() should work without problem, as it uses REML for GLMMs.

**Comment by cvoeten** [comment]
I've reworked forward() as well, and these four now all seem to do the right thing:
```
bm.test <- buildmer(cbind(incidence,size - incidence) ~ period + (1 | herd),family=binomial,data=cbpp)
bm.test <- buildmer(cbind(incidence,size - incidence) ~ period + (1 | herd),family=binomial,data=cbpp,direction='forward')
bm.test <- buildmer(cbind(incidence,size - incidence) ~ period + (1 | herd),family=binomial,data=cbpp,crit='AIC')
bm.test <- buildmer(cbind(incidence,size - incidence) ~ period + (1 | herd),family=binomial,data=cbpp,direction='forward',crit='AIC')
```
Can you install buildmer from github and test both forward and backward with your real data as well?

**Comment by tmvchan** [comment]
Sorry for the delay - confirming that both backward and forward work with my data. Thank you for the fix!

**Comment by cvoeten** [comment]
OK, great! I'll close the issue, and I've added your examples to the documentation so they'll be run as tests from now on
