### ISSUE TITLE
Conflict with latest lme4/Matrix package

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [cvoeten/buildmer#20]
If I load the buildmer and lme4 package, there are conflicts created when I run a summary() on a fitted glmer object. 
I get the error message
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
but if I detach the package, this seems to fix the problem..

I'm no expert, but it appears that the diag() function has been redefined somehow.

Thanks
Carl Schwarz

See example Rmd and output file.
[lme4-problem.txt](https://github.com/cvoeten/buildmer/files/9789376/lme4-problem.txt)
[lme4-problem.pdf](https://github.com/cvoeten/buildmer/files/9789379/lme4-problem.pdf)

**Comment by cvoeten** [comment]
Thank you for reporting this issue. It is possible that it is related to buildmer, since buildmer indeed does add an S3 generic for `diag()`. However, I can't reproduce this locally (on Windows), and it wasn't flagged in the automated tests either (which it should have, given that there's a failing example as well - issue #21).

The CRAN checks aren't experiencing this problem, not even on macOS. So my first guess is that this is a local configuration problem on your side. Could you perhaps try deleting (or temporarily renaming) your R folder, then reinstalling your packages? Preferably from R itself rather than from RStudio, because I do not know how RStudio might further be hooking into things. If the issue then does not reappear, then we'll have confirmed that it is a local problem and not a bug in buildmer. But if you still can reproduce it, then it is a bit more concerning that I can't.

I'll be back in the office on Monday; there, I have a Mac, and will see if I can reproduce the problem. If so, this may be a Mac-specific bug in buildmer. A priori, that would be somewhat unexpected, since there is no platform-specific code in buildmer. But until we understand what's happening, we certainly have to keep the option open.

**Comment by cschwarz-stat-sfu-ca** [comment]
Thanks for your feedback...

So, I created a new (blank) Rlibs and just installed lme4 and buildmer
packages (plus any dependants) using vanilla R.
I also download and reinstalled R.
Opened vanilla R and ran the sample code and it also failed (see below).
I copied and pasted the example in to the R console and it also failed (see
below)

So... very strange...

Carl


----------------------------------------------------
------------ Test example 1 ------------------
R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[R.app GUI 1.79 (8095) x86_64-apple-darwin17.0]

> library(buildmer)
> library(lme4)
Loading required package: Matrix
>
> nrow <- 100
>
> test <- data.frame(x01=runif(nrow),
+                    y=runif(nrow)<.1, block=as.factor(floor((1:nrow)/50)))
> head(test)
         x01     y block
1 0.69042359 FALSE     0
2 0.50765891 FALSE     0
3 0.55323232 FALSE     0
4 0.05477529 FALSE     0
5 0.41533901 FALSE     0
6 0.71136961 FALSE     0
>
>
> fit.model <- lme4::glmer(y~x01 + (1|block), data=test,
+                    family=binomial(link="logit"))
boundary (singular) fit: see help('isSingular')
> fit.model # this works
Generalized linear mixed model fit by maximum likelihood (Laplace
Approximation) ['glmerMod']
 Family: binomial  ( logit )
Formula: y ~ x01 + (1 | block)
   Data: test
     AIC      BIC   logLik deviance df.resid
 45.2846  53.1001 -19.6423  39.2846       97
Random effects:
 Groups Name        Std.Dev.
 block  (Intercept) 0
Number of obs: 100, groups:  block, 3
Fixed Effects:
(Intercept)          x01
     -2.462       -1.072
optimizer (Nelder_Mead) convergence code: 0 (OK) ; 0 optimizer warnings; 1
lme4 warnings
>
> class(fit.model)
[1] "glmerMod"
attr(,"package")
[1] "lme4"
>
> summary(fit.model)
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
>


----------------------------------------------------
------------ Test example 2 ------------------
-------------Example from buildmer help file.


R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[R.app GUI 1.79 (8095) x86_64-apple-darwin17.0]


> library(buildmer)
> model <- buildmer(Reaction ~ Days + (Days|Subject),lme4::sleepstudy)
Determining predictor order
Fitting via lm: Reaction ~ 1
Currently evaluating LRT for: Days
Fitting via lm: Reaction ~ 1 + Days
Updating formula: Reaction ~ 1 + Days
Fitting via gam, with REML: Reaction ~ 1 + Days
Currently evaluating LRT for: 1 | Subject
Fitting via lmer, with REML: Reaction ~ 1 + Days + (1 | Subject)
Updating formula: Reaction ~ 1 + Days + (1 | Subject)
Currently evaluating LRT for: Days | Subject
Fitting via lmer, with REML: Reaction ~ 1 + Days + (1 + Days | Subject)
Updating formula: Reaction ~ 1 + Days + (1 + Days | Subject)
Fitting ML and REML reference models
Fitting via lmer, with REML: Reaction ~ 1 + Days + (1 + Days | Subject)
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 + Days | Subject)
Testing terms
Fitting via lmer, with REML: Reaction ~ 1 + Days + (1 | Subject)
  grouping term           block     score Iteration         LRT
1     <NA>    1         NA NA 1        NA         1          NA
2     <NA> Days      NA NA Days -32.67300         1          NA
3  Subject    1    NA Subject 1 -57.53561         1          NA
4  Subject Days NA Subject Days -21.99890         1 2.79253e-10
All terms are significant
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
>
> # Tests from github issue #2, that also show the use of the 'direction'
and 'crit' parameters:
> bm.test <- buildmer(cbind(incidence,size - incidence) ~ period + (1 |
herd),
+ family=binomial,data=lme4::cbpp)
Determining predictor order
Fitting via glm: cbind(incidence, size - incidence) ~ 1
Currently evaluating LRT for: period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Updating formula: cbind(incidence, size - incidence) ~ 1 + period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Currently evaluating LRT for: 1 | herd
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period
+ (1 | herd)
Updating formula: cbind(incidence, size - incidence) ~ 1 + period + (1 |
herd)
Fitting ML and REML reference models
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period
+ (1 | herd)
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period
+ (1 | herd)
Testing terms
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + (1 |
herd)
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
  grouping   term        block      score Iteration          LRT
1     <NA>      1      NA NA 1         NA         1           NA
2     <NA> period NA NA period -18.706656         1 1.151006e-05
3     herd      1    NA herd 1  -9.303008         1 9.114967e-05
All terms are significant
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
> bm.test <- buildmer(cbind(incidence,size - incidence) ~ period + (1 |
herd),
+
family=binomial,data=lme4::cbpp,buildmerControl=buildmerControl(direction='forward'))
Determining predictor order
Fitting via glm: cbind(incidence, size - incidence) ~ 1
Currently evaluating LRT for: period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Updating formula: cbind(incidence, size - incidence) ~ 1 + period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Currently evaluating LRT for: 1 | herd
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period
+ (1 | herd)
Updating formula: cbind(incidence, size - incidence) ~ 1 + period + (1 |
herd)
  grouping   term        block        score
1     <NA>      1      NA NA 1           NA
2     <NA> period NA NA period 7.512809e-09
3     herd      1    NA herd 1 9.114967e-05
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period
+ (1 | herd)
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
> bm.test <- buildmer(cbind(incidence,size - incidence) ~ period + (1 |
herd),
+
family=binomial,data=lme4::cbpp,buildmerControl=buildmerControl(crit='AIC'))
Determining predictor order
Fitting via glm: cbind(incidence, size - incidence) ~ 1
Currently evaluating AIC for: period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Updating formula: cbind(incidence, size - incidence) ~ 1 + period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Currently evaluating AIC for: 1 | herd
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period
+ (1 | herd)
Updating formula: cbind(incidence, size - incidence) ~ 1 + period + (1 |
herd)
Fitting ML and REML reference models
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period
+ (1 | herd)
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period
+ (1 | herd)
Testing terms
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + (1 |
herd)
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
  grouping   term        block     score Iteration       AIC
1     <NA>      1      NA NA 1        NA         1        NA
2     <NA> period NA NA period -34.71577         1 -19.60994
3     herd      1    NA herd 1 -12.00527         1 -12.00527
All terms are significant
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
> bm.test <- buildmer(cbind(incidence,size - incidence) ~ period + (1 |
herd),
+ family=binomial,data=lme4::cbpp,
+ buildmerControl=buildmerControl(direction='forward',crit='AIC'))
Determining predictor order
Fitting via glm: cbind(incidence, size - incidence) ~ 1
Currently evaluating AIC for: period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Updating formula: cbind(incidence, size - incidence) ~ 1 + period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Currently evaluating AIC for: 1 | herd
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period
+ (1 | herd)
Updating formula: cbind(incidence, size - incidence) ~ 1 + period + (1 |
herd)
  grouping   term        block     score
1     <NA>      1      NA NA 1        NA
2     <NA> period NA NA period -34.71577
3     herd      1    NA herd 1 -12.00527
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period
+ (1 | herd)
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
>
> # Example showing use of the 'include' parameter to force a particular
term into the model
> m1 <- buildmer(Reaction ~
Days,data=lme4::sleepstudy,buildmerControl=list(include=~(1|Subject)))
Determining predictor order
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
Currently evaluating LRT for: Days
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Updating formula: Reaction ~ 1 + Days + (1 | Subject)
Fitting ML reference model
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Testing terms
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
  grouping term      block     score Iteration          LRT
1     <NA>    1       <NA>        NA         1           NA
2  Subject    1       <NA>        NA         1           NA
3     <NA> Days NA NA Days -60.84419         1 3.764461e-27
All terms are significant
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
> # the below are equivalent
> m2 <- buildmer(Reaction ~
Days,data=lme4::sleepstudy,buildmerControl=list(include='(1|Subject)'))
Determining predictor order
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
Currently evaluating LRT for: Days
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Updating formula: Reaction ~ 1 + Days + (1 | Subject)
Fitting ML reference model
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Testing terms
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
  grouping term      block     score Iteration          LRT
1  Subject    1       <NA>        NA         1           NA
2     <NA>    1    NA NA 1        NA         1           NA
3     <NA> Days NA NA Days -60.84419         1 3.764461e-27
All terms are significant
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
> m3 <- buildmer(Reaction ~ Days +
(1|Subject),data=lme4::sleepstudy,buildmerControl=list(
+ include=~(1|Subject)))
Determining predictor order
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
Currently evaluating LRT for: Days
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Updating formula: Reaction ~ 1 + Days + (1 | Subject)
Fitting ML reference model
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Testing terms
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
  grouping term      block     score Iteration          LRT
1     <NA>    1       <NA>        NA         1           NA
2  Subject    1       <NA>        NA         1           NA
3     <NA> Days NA NA Days -60.84419         1 3.764461e-27
All terms are significant
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
> m4 <- buildmer(Reaction ~ Days +
(1|Subject),data=lme4::sleepstudy,buildmerControl=list(
+ include='(1|Subject)'))
Determining predictor order
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
Currently evaluating LRT for: Days
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Updating formula: Reaction ~ 1 + Days + (1 | Subject)
Fitting ML reference model
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Testing terms
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
  grouping term      block     score Iteration          LRT
1  Subject    1       <NA>        NA         1           NA
2     <NA>    1    NA NA 1        NA         1           NA
3     <NA> Days NA NA Days -60.84419         1 3.764461e-27
All terms are significant
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
>

**Comment by cvoeten** [comment]
I'm sorry, I still can't reproduce it. This is on a fully-updated Mac:

```
R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin21.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(buildmer)
library(lme4)

nrow <- 100

test <- data.frame(x01=runif(nrow), 
                   y=runif(nrow)<.1, block=as.factor(floor((1:nrow)/50)))
head(test)


fit.model <- lme4::glmer(y~x01 + (1|block), data=test,
                   family=binomial(link="logit"))
fit.model # this works

class(fit.model)

summary(fit.model)
vcov(fit.model)
Loading required package: Matrix
         x01     y block
1 0.73956505 FALSE     0
2 0.35462849 FALSE     0
3 0.25443997 FALSE     0
4 0.89124969 FALSE     0
5 0.02168318 FALSE     0
6 0.96982355 FALSE     0
Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: binomial  ( logit )
Formula: y ~ x01 + (1 | block)
   Data: test
     AIC      BIC   logLik deviance df.resid 
 95.2202 103.0357 -44.6101  89.2202       97 
Random effects:
 Groups Name        Std.Dev.
 block  (Intercept) 0.2535  
Number of obs: 100, groups:  block, 3
Fixed Effects:
(Intercept)          x01  
     -1.009       -1.271  
[1] "glmerMod"
attr(,"package")
[1] "lme4"
Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: binomial  ( logit )
Formula: y ~ x01 + (1 | block)
   Data: test

     AIC      BIC   logLik deviance df.resid 
    95.2    103.0    -44.6     89.2       97 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-0.6359 -0.4862 -0.3998 -0.3291  2.6887 

Random effects:
 Groups Name        Variance Std.Dev.
 block  (Intercept) 0.06428  0.2535  
Number of obs: 100, groups:  block, 3

Fixed effects:
            Estimate Std. Error z value Pr(>|z|)  
(Intercept)  -1.0091     0.5713  -1.766   0.0773 .
x01          -1.2705     1.0115  -1.256   0.2091  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
    (Intr)
x01 -0.810
2 x 2 Matrix of class "dpoMatrix"
            (Intercept)        x01
(Intercept)   0.3263333 -0.4678231
x01          -0.4678231  1.0231321
```

**Comment by cschwarz-stat-sfu-ca** [comment]
Hmmm.... very strange...

Could you please send me the sessionInfo() on your run so we can see that
the versions of all our packages match.
This is my sessionInfo()

R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6

Matrix products: default
BLAS:
/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
LAPACK:
/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] buildmer_2.6 lme4_1.1-30  Matrix_1.5-1

loaded via a namespace (and not attached):
 [1] minqa_1.2.4     MASS_7.3-58.1   compiler_4.2.1  Rcpp_1.0.9
 splines_4.2.1   nlme_3.1-160    grid_4.2.1      nloptr_2.0.3
 boot_1.3-28     lattice_0.20-45
>

Do you know where your code would call the dgeMatrix_getDiag routine?

I see in the Matrix package, the code for dgeMatrix.R has the following
code snippet at around line 19
## MJ: no longer needed ... replacement in ./unpackedMatrix.R
if (FALSE) {
..get.diag <- function(x, nrow, ncol, names=TRUE) {
    ##         vvvvvvvvvvvvvvvvv here just a place holder, replaced in
.mkSpec.diag()
    y <- .Call(dgeMatrix_getDiag, x) # double or logical
    if(names) {
        nms <- dimnames(x)
        if(is.list(nms) && !any(vapply(nms, is.null, NA)) &&
           identical((nm <- nms[[1L]][im <- seq_len(min(dim(x)))]),
nms[[2L]][im]))
            names(y) <- nm
    }
    y
}
.mkSpec.diag <- function(symb) {
    rr <- ..get.diag
    body(rr)[[2]][[3]][[2]] <- symb
    rr
}
.dge.diag <- .mkSpec.diag(quote(dgeMatrix_getDiag))

setMethod("t", signature(x = "dgeMatrix"), t_geMatrix)
setMethod("diag", signature(x = "dgeMatrix"), .dge.diag)
setMethod("diag<-", signature(x = "dgeMatrix"),
 function(x, value) .Call(dgeMatrix_setDiag, x, value))
} ## MJ

which seems to indicate that degMatrix_getDiag is no longer used (?) but
I'm no expert on S4classes.

I'm grasping at straws here.

Carl

**Comment by cschwarz-stat-sfu-ca** [comment]
Some more interesting information...

If I install Matrix and buildmer from SOURCE (i.e. the tar.gz files
downloaded from the CRAN site), then the problem disappears, i.e. code
works without problem.
However if I install Matrix and buildmer using the versions from CRAN, the
problem appears.

I'm guessing that there is some C code that is never referenced and so gets
stripped from the CRAN version.

I went through all the possible combinations:
Matrix  buildmer
Source  Source  - code works without problem
Binary   Source - code has error
Source Binary -  code has error
Binary   Binary  - code has error

Does this help? I've a feeling we're not in Kansas anymore ...

Carl

**Comment by cvoeten** [comment]
sessionInfo():

```
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin21.6.0 (64-bit)
Running under: macOS Monterey 12.6

Matrix products: default
BLAS:   /usr/local/Cellar/openblas/0.3.21/lib/libopenblasp-r0.3.21.dylib
LAPACK: /usr/local/Cellar/r/4.2.1_4/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.1
```

re `diag`: all that buildmer is doing is https://github.com/cvoeten/buildmer/blob/main/R/buildmer-S4.R#L120-L144. So you should be able to reproduce the error by just copy-pasting those lines of code without attaching buildmer.

buildmer does not contain any compiled code, so source or binary should not make a difference for it beyond the slightly longer installation time for source builds. Similarly, the problem you're facing does not involve C code in any way - the error you're getting refers to a missing R method.

I don't know what to advise at this point - maybe ask the r-help mailing list? I'll leave this open in case one of us does reach the conclusion that it's a bug in buildmer, but at the moment I can't see how it would be.

**Comment by cschwarz-stat-sfu-ca** [comment]
Interesting....I tried a reinstall of both (binary) packages from CRAN
without problems on my ARM machine...

I'll submit a note to the R-devel mailing list to see if anyone has some
suggestions.

In the meantime, by using a source install, my code works so I can go
forward while the gurus work on this..

Thanks for all your help

Carl.

**Comment by cschwarz-stat-sfu-ca** [comment]
I posted to the r-package-devel site and got a response from Duncan Murdoch
(below).
He suggests that when you submitted buildmer to CRAN an older version of
Matrix was around and so part of the old version are "included" in the
binary package.
He suggests that you resubmit buildmer to CRAN to have it rebuilt with the
current version of Matrix around.

Carl.

I see the same thing.  This sounds like a problem in the handling of
> methods that has been discussed somewhat recently:


   https://stat.ethz.ch/pipermail/r-devel/2022-September/081971.html

The problem is that when the binary is built, some code from other
> packages is kept as part of it.  When that other package is updated, you
> need a new source install of your own package (or a rebuild at CRAN to
> replace the binary) to cache the new code.


This can also be done explicitly by package startup code; I think this
> thread


   https://stat.ethz.ch/pipermail/r-package-devel/2022q3/008481.html

turned out to be a case where rstan was caching something, and an update
> to ggplot2 didn't work with the cached data.  Given the error message,
> your issue sounds more like the first one.


I don't recall if there was a resolution.  Maybe you can ask the CRAN
> maintainers to rebuild buildmer.


Duncan Murdoch

**Comment by cvoeten** [comment]
This doesn’t make much sense to me – packages, including those declaring S3 methods, are built against slightly different versions of transitive dependencies all the time, and this is my first time seeing this. I also find it odd that this apparently only happened on macOS, and not on other platforms, even though updates to Matrix should make it to all platforms simultaneously. But the fix seems to be easy: I can just release a new version of buildmer. I’ll start preparing to do so.
 �
Thank you for your persistence in digging into this issue.

**Comment by cschwarz-stat-sfu-ca** [comment]
And the reply from the maintainer for Matrix

>>>>> Duncan Murdoch
>>>>>     on Tue, 18 Oct 2022 15:17:33 -0400 writes:

    > I see the same thing.  This sounds like a problem in the handling of
    > methods that has been discussed somewhat recently:

    > https://stat.ethz.ch/pipermail/r-devel/2022-September/081971.html

    > The problem is that when the binary is built, some code from other
    > packages is kept as part of it.  When that other package is updated,
you
    > need a new source install of your own package (or a rebuild at CRAN to
    > replace the binary) to cache the new code.

    > This can also be done explicitly by package startup code; I think this
    > thread

    > https://stat.ethz.ch/pipermail/r-package-devel/2022q3/008481.html

    > turned out to be a case where rstan was caching something, and an
update
    > to ggplot2 didn't work with the cached data.  Given the error message,
    > your issue sounds more like the first one.

    > I don't recall if there was a resolution.  Maybe you can ask the CRAN
    > maintainers to rebuild buildmer.

    > Duncan Murdoch

Yes, thank you, Duncan!

The binary version of 'builmer' (or also lme4 ?) must have been created
with an older version of Matrix  (which did not have the
dgeMatrix_getDiag C code)  and the respective maintainer of the
binary builds (*) must rebuild the binary versions of those
Matrix-reverse-dependant packages,
---
*) in this case the macOS ones (both for Intel and ARM Macs)

Martin Maechler
(maintainer of Matrix)

**Comment by cschwarz-stat-sfu-ca** [comment]
And the reply from Uwe why the problem doesn't happen on WIndows... Crl.

Please let the Simon (Mac maintainer for CRAN) know.
For Windows, the revdeps get rebuild automatically.

Best,
Uwe Ligges

**Comment by cvoeten** [comment]
Thanks again for your extensive detective work, and good of you to think of asking r-pkg-devel - it seemed more like an r-help problem to me, but you made the better call.

I've just pushed v2.7 to CRAN - it's time for a new release anyway. It should make its way there in a short while, without the need to bother Simon Urbanek.

**Comment by apike02** [comment]
Related to this - reinstalling buildmer from this github version (I think 2.7, but not tagged yet) solved my problem too - it was related, I think. My error was 'trying to get slot "call" from an object (class "try-error") that is not an S4 object' which was only present when running clusterperm.lmer with random effects (removing random effect terms solved it, for some reason). Hopefully if anyone googles this error this will show up! (I now get

**Comment by cschwarz-stat-sfu-ca** [comment]
Yes, the new build of buildmer solved the problem. Carl
