### ISSUE TITLE
Example for buildmer also fails with same error as in previous issue.

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [cvoeten/buildmer#21]
This related to the previous issue. The example for buildmer does not run and results in the same error.
Here is the output from running the Example from buildmer with extra blank lines showing the error message.

This was run in a naked Rstudio session.

Thanks

### ** Examples

library(buildmer)
model <- buildmer(Reaction ~ Days + (Days|Subject),lme4::sleepstudy)
Determining predictor order
Fitting via lm: Reaction ~ 1
Currently evaluating LRT for: Days
Fitting via lm: Reaction ~ 1 + Days
Updating formula: Reaction ~ 1 + Days
Fitting via gam, with REML: Reaction ~ 1 + Days
Currently evaluating LRT for: 1 | Subject
Fitting via lmer, with REML: Reaction ~ 1 + Days + (1 | Subject)
Updating formula: Reaction ~ 1 + Days + (1 | Subject)
Currently evaluating LRT for: Days | Subject
Fitting via lmer, with REML: Reaction ~ 1 + Days + (1 + Days | Subject)
Updating formula: Reaction ~ 1 + Days + (1 + Days | Subject)
Fitting ML and REML reference models
Fitting via lmer, with REML: Reaction ~ 1 + Days + (1 + Days | Subject)
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 + Days | Subject)
Testing terms
Fitting via lmer, with REML: Reaction ~ 1 + Days + (1 | Subject)
  grouping term           block     score Iteration         LRT
1     <NA>    1         NA NA 1        NA         1          NA
2     <NA> Days      NA NA Days -32.67300         1          NA
3  Subject    1    NA Subject 1 -57.53561         1          NA
4  Subject Days NA Subject Days -21.99890         1 2.79253e-10
All terms are significant
Finalizing by converting the model to lmerTest

Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
Error in buildmer(Reaction ~ Days + (Days | Subject), lme4::sleepstudy): trying to get slot "call" from an object (class "try-error") that is not an S4 object 

# Tests from github issue #2, that also show the use of the 'direction' and 'crit' parameters:
bm.test <- buildmer(cbind(incidence,size - incidence) ~ period + (1 | herd),
        family=binomial,data=lme4::cbpp)
Determining predictor order
Fitting via glm: cbind(incidence, size - incidence) ~ 1
Currently evaluating LRT for: period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Updating formula: cbind(incidence, size - incidence) ~ 1 + period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Currently evaluating LRT for: 1 | herd
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
Updating formula: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
Fitting ML and REML reference models
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
Testing terms
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + (1 | herd)
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
  grouping   term        block      score Iteration          LRT
1     <NA>      1      NA NA 1         NA         1           NA
2     <NA> period NA NA period -18.706656         1 1.151006e-05
3     herd      1    NA herd 1  -9.303008         1 9.114967e-05
All terms are significant

Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found

bm.test <- buildmer(cbind(incidence,size - incidence) ~ period + (1 | herd),
        family=binomial,data=lme4::cbpp,buildmerControl=buildmerControl(direction='forward'))
Determining predictor order
Fitting via glm: cbind(incidence, size - incidence) ~ 1
Currently evaluating LRT for: period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Updating formula: cbind(incidence, size - incidence) ~ 1 + period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Currently evaluating LRT for: 1 | herd
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
Updating formula: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
  grouping   term        block        score
1     <NA>      1      NA NA 1           NA
2     <NA> period NA NA period 7.512809e-09
3     herd      1    NA herd 1 9.114967e-05
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)

Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found

bm.test <- buildmer(cbind(incidence,size - incidence) ~ period + (1 | herd),
        family=binomial,data=lme4::cbpp,buildmerControl=buildmerControl(crit='AIC'))
Determining predictor order
Fitting via glm: cbind(incidence, size - incidence) ~ 1
Currently evaluating AIC for: period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Updating formula: cbind(incidence, size - incidence) ~ 1 + period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Currently evaluating AIC for: 1 | herd
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
Updating formula: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
Fitting ML and REML reference models
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
Testing terms
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + (1 | herd)
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
  grouping   term        block     score Iteration       AIC
1     <NA>      1      NA NA 1        NA         1        NA
2     <NA> period NA NA period -34.71577         1 -19.60994
3     herd      1    NA herd 1 -12.00527         1 -12.00527
All terms are significant
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
bm.test <- buildmer(cbind(incidence,size - incidence) ~ period + (1 | herd),
        family=binomial,data=lme4::cbpp,
        buildmerControl=buildmerControl(direction='forward',crit='AIC'))
Determining predictor order
Fitting via glm: cbind(incidence, size - incidence) ~ 1
Currently evaluating AIC for: period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Updating formula: cbind(incidence, size - incidence) ~ 1 + period
Fitting via glm: cbind(incidence, size - incidence) ~ 1 + period
Currently evaluating AIC for: 1 | herd
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
Updating formula: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
  grouping   term        block     score
1     <NA>      1      NA NA 1        NA
2     <NA> period NA NA period -34.71577
3     herd      1    NA herd 1 -12.00527
Fitting via glmer, with ML: cbind(incidence, size - incidence) ~ 1 + period + (1 | herd)
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
# Example showing use of the 'include' parameter to force a particular term into the model
m1 <- buildmer(Reaction ~ Days,data=lme4::sleepstudy,buildmerControl=list(include=~(1|Subject)))
Determining predictor order
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
Currently evaluating LRT for: Days
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Updating formula: Reaction ~ 1 + Days + (1 | Subject)
Fitting ML reference model
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Testing terms
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
  grouping term      block     score Iteration          LRT
1     <NA>    1       <NA>        NA         1           NA
2  Subject    1       <NA>        NA         1           NA
3     <NA> Days NA NA Days -60.84419         1 3.764461e-27
All terms are significant
Finalizing by converting the model to lmerTest
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
Error in buildmer(Reaction ~ Days, data = lme4::sleepstudy, buildmerControl = list(include = ~(1 | : trying to get slot "call" from an object (class "try-error") that is not an S4 object 
# the below are equivalent
m2 <- buildmer(Reaction ~ Days,data=lme4::sleepstudy,buildmerControl=list(include='(1|Subject)'))
Determining predictor order
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
Currently evaluating LRT for: Days
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Updating formula: Reaction ~ 1 + Days + (1 | Subject)
Fitting ML reference model
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Testing terms
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
  grouping term      block     score Iteration          LRT
1  Subject    1       <NA>        NA         1           NA
2     <NA>    1    NA NA 1        NA         1           NA
3     <NA> Days NA NA Days -60.84419         1 3.764461e-27
All terms are significant
Finalizing by converting the model to lmerTest
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
Error in buildmer(Reaction ~ Days, data = lme4::sleepstudy, buildmerControl = list(include = "(1|Subject)")): trying to get slot "call" from an object (class "try-error") that is not an S4 object 
m3 <- buildmer(Reaction ~ Days + (1|Subject),data=lme4::sleepstudy,buildmerControl=list(
        include=~(1|Subject)))
Determining predictor order
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
Currently evaluating LRT for: Days
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Updating formula: Reaction ~ 1 + Days + (1 | Subject)
Fitting ML reference model
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Testing terms
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
  grouping term      block     score Iteration          LRT
1     <NA>    1       <NA>        NA         1           NA
2  Subject    1       <NA>        NA         1           NA
3     <NA> Days NA NA Days -60.84419         1 3.764461e-27
All terms are significant
Finalizing by converting the model to lmerTest
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
Error in buildmer(Reaction ~ Days + (1 | Subject), data = lme4::sleepstudy, : trying to get slot "call" from an object (class "try-error") that is not an S4 object 
m4 <- buildmer(Reaction ~ Days + (1|Subject),data=lme4::sleepstudy,buildmerControl=list(
        include='(1|Subject)'))
Determining predictor order
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
Currently evaluating LRT for: Days
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Updating formula: Reaction ~ 1 + Days + (1 | Subject)
Fitting ML reference model
Fitting via lmer, with ML: Reaction ~ 1 + Days + (1 | Subject)
Testing terms
Fitting via lmer, with ML: Reaction ~ 1 + (1 | Subject)
  grouping term      block     score Iteration          LRT
1  Subject    1       <NA>        NA         1           NA
2     <NA>    1    NA NA 1        NA         1           NA
3     <NA> Days NA NA Days -60.84419         1 3.764461e-27
All terms are significant
Finalizing by converting the model to lmerTest
Error in diag(from, names = FALSE) : object 'dgeMatrix_getDiag' not found
Error in buildmer(Reaction ~ Days + (1 | Subject), data = lme4::sleepstudy, : trying to get slot "call" from an object (class "try-error") that is not an S4 object

**Comment by cvoeten** [comment]
I'll close this one as it's the same problem as issue #20.
