### ISSUE TITLE
Option to specify the alpha level for Likelihood Ratio Tests in buildmer()

### ISSUE THREAD

**Issue by alexenge** [cvoeten/buildmer#5]
Dear Cesko,

First of all, thanks a lot for your work on this fantastic package! It's very useful and versatile indeed.

I've just wondered recently—and probably this is a really stupid question—whether it would make sense to include an option for the user to specify the critical alpha level which determines whether or not an LRT is considered significant. Matuschek et al. (2017, _JML_) used α = .20, which is consistent with what they teach in stats class that one should use a more liberal alpha level when the null is desired (given that we want to hang on to the more parsimonious model).

I could not find any information on which alpha level is used in `builmder()` and wondered whether it would be possible to be a bit more explicit about this or, better yet, allow the user to specify an alpha level for the LRT-based model selection.

Best
Alexander

**Comment by cvoeten** [comment]
Some quick answers/notes for now:

  - Currently, the alpha is fixed at .05. The relevant function is `buildmer:::elim.LRT`, which you'll see is just `exp(logp) >= 0.05` (for technical reasons, the argument passed to this function is the *log* p-value)
  - To quickly get what you want right now, you can pass your own `elim` function, e.g. `buildmerControl=list(elim=function (logp) exp(logp) >= .2)`. This should 'just work' even with `buildmer()`.
  - It makes sense to explicitly make this configurable. But I need to think about the best way to implement it:
     - Ideally, we would want to add an `alpha` option to `buildmerControl`. But I believe `alpha` is also used by `glmertree` for controlling the splitting criterion in `buildmertree`.
     - With the recent switch for control arguments from `buildmer(...)` to `buildmer(buildmerControl=list(...))`, this clash shouldn't be a problem: the `alpha` meant for `glmertree` should go in `buildmertree` and the alpha meant for buildmer control should go into `buildmerControl`. But, for legacy reasons, this is not how it works in practice: rather, all options that overlap with `buildmerControl` names go into `buildmerControl` unconditionally, with those in the dots arguments always overriding those in the control arguments. This cannot be changed without breaking legacy (pre-1.7.1) code.
     - Options:
       - Name it something like `alpha.buildmer`, or `al` to be consistent with `cl`, which has the same problem (it could not be named `cluster` because `bam` accepts a `cluster` option)
       - Use a completely different design, e.g. create a closure on `elim.LRT` that sets the alpha appropriately (but that may be very fragile?)
       - Suggestions welcome!

**Comment by alexenge** [comment]
Thanks a lot for your quick reply! I wasn't aware of this naming issue. I think it would be very helpful to have an option directly within `buildmerControl()` (and `buildmer()` for legacy reasons) and I see no problem with naming it `al` as long as it's described in the help page. Alternative names I could think of would be `cutoff` or `significance` (if they aren't used by other functions), or, because the option would apply only to LRTs (and not for instance to AIC/BIC), something like `lrt.alpha`).

By the way, the current workaround using the `elim` argument works like charm! Thanks a lot.

**Comment by cvoeten** [comment]
v2.1, which just made it to CRAN, a adds function `LRTalpha()` that generates the required `elim` function to have a requested alpha level. I'm amazed that it took me a year to come up with the very simple idea of a function returning a closure that incorporates the custom alpha parameter, but you have it now!

**Comment by alexenge** [comment]
This works like charm. Thanks so much!
